### ISSUE TITLE
Non riesco ad aprire l'addon

### ISSUE THREAD

**Issue by orisystech** [Fenice82/plugin.video.streamondemand-pureita#42]
non riesco ad aprire l'addon il log mi da degli errori: 

20:35:38.316 T:140290828146432   ERROR: GetDirectory - Error getting
20:36:11.282 T:140298339714816   ERROR: Previous line repeats 2 times.
20:36:11.282 T:140298339714816 WARNING: CSkinInfo: failed to load skin settings
20:36:11.290 T:140298339714816   ERROR: EXCEPTION: XML File for Window is missing
20:36:11.290 T:140298339714816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "/home/orisystech/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 50, in <module>
                                                window = navigation.get_window_for_item( item )
                                              File "/home/orisystech/.kodi/addons/plugin.video.streamondemand-pureita-master/navigation.py", line 294, in get_window_for_item
                                                window = window_channels.ChannelWindow("banner.xml",plugintools.get_runtime_path())
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--

**Comment by orione7** [comment]
Ciao, fai un'installazione pulita cancellando anche i file della PureITA nella cartella "Userdata" di Kodi poi  scarica la nuova versione ed installa regolarmente

**Comment by paolantoni** [comment]
Il problema persiste persiste. Installazione di OSMC versione 2017.02-02 Kernel 4.4.27-7.

**Comment by orione7** [comment]
Se sei  con kodi Kripton cambia skyn e installa "Confluence".  Eventualmente  non risolvi devi caricare il log completo su pastebin.

**Comment by paolantoni** [comment]
Con la skin Confluence funziona. Considera però che con Kodi Kripton non è la skin di default, e sembra avere qualche problema.

**Comment by orione7** [comment]
Dalle nostre prove risulta che solo con OSMC e solo su alcuni device  puo' dare problemi con skyn diverse da "Confluence" altrimenti se si utilizza Openelec, Libreelec, Widnows 10, non risulta alcun problema e in nessuna Skyn per cui se vuoi continuare ad utilizzare il Plugin con OSMC non ti resta che rimanere con la Skyn Confluence almeno fino a quando OSMC non faccia un Update di versione.

**Comment by Doc73** [comment]
Confermo, dalle mie prove, che NON funziona su:
- Debian Jessie con Kodi 16.1 con tema diverso da Confluence
- Android con Kodi 17.1 con temi Estuary (che è il default) e Estouchy

Più tardi provo su OSMC.
